### ISSUE TITLE
SERVER DOWN

### ISSUE THREAD

**Issue by pavan2108** [Mau-MD/linkedin_github_readme#1]
The server problem was caused by the host of the application stopping their free dyno. Fix the problem, please.

**Comment by Mau-MD** [comment]
That's true! I will find another place to host this project by the end of the week. Just remember you will have to re-generate the link again. I will tag you once this is done

**Comment by Mau-MD** [comment]
@pavan2108 Hello! Just found a new hosting provider! The app should be live now, just generate a new URL again

**Comment by pavan2108** [comment]
Thank you
